# Generated by Django 4.2.2 on 2023-07-01 16:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='apply_instructions',
            field=tinymce.models.HTMLField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='apply_link',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='degree',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='requirements',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
