# Generated by Django 4.2.2 on 2023-07-01 16:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_program_apply_instructions_program_apply_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='apply_instructions',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='details',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='requirements',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
