# Generated by Django 4.2.2 on 2023-07-01 20:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_program_apply_instructions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='program',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
