# Generated by Django 4.2.2 on 2023-07-01 20:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_program_options_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='apply_instructions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
