# Generated by Django 4.2.2 on 2023-07-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_program_contact_alter_program_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
