# Generated by Django 4.2.2 on 2023-07-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_program_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='scraper.university'),
        ),
    ]
